---
title: 
output:
  html_document:
    fig_caption: yes
    number_sections: yes
geometry: left=0,right=0,top=0,bottom=0
---

```{css, echo=FALSE}
 body {
  background-color: transparent;
   color: #000000;
}
```

```{r, setup, include=FALSE}
library(rgl)
library(readobj)
library(here)
knitr::knit_hooks$set(webgl = hook_webgl)
knitr::opts_knit$set(root.dir = '/Users/Ty/Dropbox/Dendritic connectivity/SUS2020')

 bg3d( alpha=0)
lat <- matrix(seq(90,-90, len=50)*pi/180, 50, 50, byrow=TRUE)
long <- matrix(seq(-180, 180, len=50)*pi/180, 50, 50)
r <- 6378.1 # radius of Earth in km
x <- r*cos(lat)*cos(long); y <- r*cos(lat)*sin(long)
z <- r*sin(lat)

```

```{r, webgl=TRUE, echo=FALSE, warning=FALSE, error=FALSE, fig.pos = "t", fig.height=4, fig.width=6, fig.cap = "An amazing plot"}

rgl.clear()
#rgl.sprites(  12000, 0, -3000, texture = here("www/Rmarkdown_Knits/Biodiversity module/global/SOSdatasets/rainfall/colorbar.png"))
 # show2d(8000, 0, 0,file= here("www/Rmarkdown_Knits/Biodiversity module/global/SOSdatasets/rainfall/colorbar.png"), face = "y-",
 #        width = 1000, height = 480)

persp3d(x, y, z, col="white", 
          texture="www/Rmarkdown_Knits/Biodiversity module/global/SOSdatasets/rainfall/2048.PNG", 
          specular="white", axes=FALSE, box=FALSE, 
          xlab="", ylab="", zlab="",
          normal_x=x, normal_y=y, normal_z=z, lit=FALSE,polygon_offset = 1,alpha=1, add = TRUE)
  
  persp3d(x, y, z, col="white", 
          texture="www/Rmarkdown_Knits/Biodiversity module/global/SOSdatasets/rainfall/TRMM_3B43M_2015-12.PNG", 
          specular="white", axes=FALSE, box=FALSE, 
          xlab="", ylab="", zlab="",
          normal_x=x, normal_y=y, normal_z=z, lit=FALSE,alpha=0.8, add = TRUE)
  
  
 
     
    par3d(windowRect = c(0, 0, 600, 400))
    rgl.viewpoint(theta = 0, phi = -90, zoom=0.55, interactive = TRUE)
       #rglwidget(elementId = "earth")
```




```{r, webgl=TRUE, echo=FALSE, warning=FALSE, error=FALSE, fig.pos = "t", fig.height=4, fig.width=6, caption ="Global rainfall -- This figure shows the "}

rgl.clear()
#rgl.sprites(  12000, 0, -3000, texture = here("www/Rmarkdown_Knits/Biodiversity module/global/SOSdatasets/rainfall/colorbar.png"))
 # show2d(8000, 0, 0,file= here("www/Rmarkdown_Knits/Biodiversity module/global/SOSdatasets/rainfall/colorbar.png"), face = "y-",
 #        width = 1000, height = 480)

persp3d(x, y, z, col="white", 
          texture="www/Rmarkdown_Knits/Biodiversity module/global/SOSdatasets/mammals threatened/4096-background.png", 
          specular="white", axes=FALSE, box=FALSE, 
          xlab="", ylab="", zlab="",
          normal_x=x, normal_y=y, normal_z=z, lit=FALSE,polygon_offset = 1,alpha=1, add = TRUE)
  
 
     
    par3d(windowRect = c(0, 0, 600, 400))
    rgl.viewpoint(theta = 0, phi = -90, zoom=0.55, interactive = TRUE)
      rglwidget(elementId = "plot3drgl")
```

```{r, include=FALSE}
toggleWidget(sceneId = "plot3drgl",  label = "Data")
```



```{r, webgl=TRUE, echo=FALSE, warning=FALSE, error=FALSE, fig.pos = "t", fig.height=4, fig.width=6, fig.cap ="Global rainfall -- This figure shows the "}

rgl.clear()
#rgl.sprites(  12000, 0, -3000, texture = here("www/Rmarkdown_Knits/Biodiversity module/global/SOSdatasets/rainfall/colorbar.png"))
 # show2d(8000, 0, 0,file= here("www/Rmarkdown_Knits/Biodiversity module/global/SOSdatasets/rainfall/colorbar.png"), face = "y-",
 #        width = 1000, height = 480)

persp3d(x, y, z, col="white", 
          texture="www/Rmarkdown_Knits/Biodiversity module/global/SOSdatasets/mammals threatened/4096-background.png", 
          specular="white", axes=FALSE, box=FALSE, 
          xlab="", ylab="", zlab="",
          normal_x=x, normal_y=y, normal_z=z, lit=FALSE,polygon_offset = 1,alpha=1, add = TRUE)
  
 
     
    par3d(windowRect = c(0, 0, 600, 400))
    rgl.viewpoint(theta = 0, phi = -90, zoom=0.55, interactive = TRUE)
       #rglwidget(elementId = "earth")
```

